version: '3.8'

services:
  web:
    build: .
    ports:
      - "8050:8050"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./predictions:/app/predictions
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped 